apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: user-postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: user-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: userpostgresdata
      volumes:
        - name: userpostgresdata
          persistentVolumeClaim:
            claimName: user-postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres-srv
spec:
  selector:
    app: user-postgres
  ports:
    - name: user
      protocol: TCP
      port: 5432
      targetPort: 5432
