apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: qishhub/user-image
          env:
            - name: PORT
              value: "4001"
            - name: USER_POSTGRES_DB_NAME
              value: "User"
            - name: USER_POSTGRES_DB_USERNAME
              value: "admin"
            - name: USER_POSTGRES_DB_PASSWORD
              value: "admin"
            - name: USER_POSTGRES_DB_HOST
              value: "user-postgres-srv"
            - name: JWT_ACCESTOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_ACCESTOKEN_KEY
            - name: JWT_REFRESHTOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_REFRESHTOKEN_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 4001
      targetPort: 4001
