apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: auth-postgres-volume # Sets PV name
  labels:
    type: local # Sets PV's type
    app: auth-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql" # Sets PV's host path